/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: szwrap.i */

#define SWIGMODULE szwrap
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "libaec.h"

#define SZ_ALLOW_K13_OPTION_MASK         1
#define SZ_CHIP_OPTION_MASK              2
#define SZ_EC_OPTION_MASK                4
#define SZ_LSB_OPTION_MASK               8
#define SZ_MSB_OPTION_MASK              16
#define SZ_NN_OPTION_MASK               32
#define SZ_RAW_OPTION_MASK             128

#define SZ_OK AEC_OK
#define SZ_OUTBUFF_FULL 2

#define SZ_NO_ENCODER_ERROR -1
#define SZ_PARAM_ERROR AEC_CONF_ERROR
#define SZ_MEM_ERROR AEC_MEM_ERROR

#define SZ_MAX_PIXELS_PER_BLOCK 32
#define SZ_MAX_BLOCKS_PER_SCANLINE 128
#define SZ_MAX_PIXELS_PER_SCANLINE                              \
    (SZ_MAX_BLOCKS_PER_SCANLINE) * (SZ_MAX_PIXELS_PER_BLOCK)

typedef struct SZ_com_t_s
{
    int options_mask;
    int bits_per_pixel;
    int pixels_per_block;
    int pixels_per_scanline;
} SZ_com_t;

int SZ_BufftoBuffCompress(void *dest, size_t *destLen,
                          const void *source, size_t sourceLen,
                          SZ_com_t *param);
int SZ_BufftoBuffDecompress(void *dest, size_t *destLen,
                            const void *source, size_t sourceLen,
                            SZ_com_t *param);

int SZ_encoder_enabled(void);



#include <stdint.h>		// Use the C99 official header

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_szwrap_f010b74e9bb20381(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_szwrap_f010b74e9bb20381(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_SZ_MAX_PIXELS_PER_SCANLINE_szwrap_f010b74e9bb20381() {
  int result;
  intgo _swig_go_result;
  
  
  result = (128) *(32);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SZ_com_t_options_mask_set_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0, intgo _swig_go_1) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->options_mask = arg2;
  
}


intgo _wrap_SZ_com_t_options_mask_get_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  
  result = (int) ((arg1)->options_mask);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SZ_com_t_bits_per_pixel_set_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0, intgo _swig_go_1) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->bits_per_pixel = arg2;
  
}


intgo _wrap_SZ_com_t_bits_per_pixel_get_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  
  result = (int) ((arg1)->bits_per_pixel);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SZ_com_t_pixels_per_block_set_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0, intgo _swig_go_1) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->pixels_per_block = arg2;
  
}


intgo _wrap_SZ_com_t_pixels_per_block_get_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  
  result = (int) ((arg1)->pixels_per_block);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SZ_com_t_pixels_per_scanline_set_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0, intgo _swig_go_1) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->pixels_per_scanline = arg2;
  
}


intgo _wrap_SZ_com_t_pixels_per_scanline_get_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  
  result = (int) ((arg1)->pixels_per_scanline);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct SZ_com_t_s *_wrap_new_SZ_com_t_szwrap_f010b74e9bb20381() {
  struct SZ_com_t_s *result = 0 ;
  struct SZ_com_t_s *_swig_go_result;
  
  
  result = (struct SZ_com_t_s *)calloc(1, sizeof(struct SZ_com_t_s));
  *(struct SZ_com_t_s **)&_swig_go_result = (struct SZ_com_t_s *)result; 
  return _swig_go_result;
}


void _wrap_delete_SZ_com_t_szwrap_f010b74e9bb20381(struct SZ_com_t_s *_swig_go_0) {
  struct SZ_com_t_s *arg1 = (struct SZ_com_t_s *) 0 ;
  
  arg1 = *(struct SZ_com_t_s **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_SZ_BufftoBuffCompress_szwrap_f010b74e9bb20381(void *_swig_go_0, long long *_swig_go_1, void *_swig_go_2, long long _swig_go_3, struct SZ_com_t_s *_swig_go_4) {
  void *arg1 = (void *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  SZ_com_t *arg5 = (SZ_com_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(size_t **)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  arg5 = *(SZ_com_t **)&_swig_go_4; 
  
  result = (int)SZ_BufftoBuffCompress(arg1,arg2,(void const *)arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SZ_BufftoBuffDecompress_szwrap_f010b74e9bb20381(void *_swig_go_0, long long *_swig_go_1, void *_swig_go_2, long long _swig_go_3, struct SZ_com_t_s *_swig_go_4) {
  void *arg1 = (void *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  SZ_com_t *arg5 = (SZ_com_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(size_t **)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  arg4 = (size_t)_swig_go_3; 
  arg5 = *(SZ_com_t **)&_swig_go_4; 
  
  result = (int)SZ_BufftoBuffDecompress(arg1,arg2,(void const *)arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SZ_encoder_enabled_szwrap_f010b74e9bb20381() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)SZ_encoder_enabled();
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

