/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: aecwrap.i

package aecwrap

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -l:libaec.a

typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
extern void _wrap_Swig_free_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_aecwrap_14da976aa081fe6a(swig_intgo arg1);
extern void _wrap_aec_stream_next_in_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_aec_stream_next_in_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_avail_in_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_aec_stream_avail_in_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_total_in_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_aec_stream_total_in_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_next_out_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_aec_stream_next_out_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_avail_out_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_aec_stream_avail_out_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_total_out_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_aec_stream_total_out_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_bits_per_sample_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_stream_bits_per_sample_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_block_size_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_stream_block_size_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_rsi_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_stream_rsi_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_flags_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_stream_flags_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern void _wrap_aec_stream_state_set_aecwrap_14da976aa081fe6a(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_aec_stream_state_get_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern uintptr_t _wrap_new_aec_stream_aecwrap_14da976aa081fe6a(void);
extern void _wrap_delete_aec_stream_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_AEC_CONF_ERROR_aecwrap_14da976aa081fe6a(void);
extern swig_intgo _wrap_AEC_STREAM_ERROR_aecwrap_14da976aa081fe6a(void);
extern swig_intgo _wrap_AEC_DATA_ERROR_aecwrap_14da976aa081fe6a(void);
extern swig_intgo _wrap_AEC_MEM_ERROR_aecwrap_14da976aa081fe6a(void);
extern swig_intgo _wrap_aec_encode_init_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_aec_encode_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_encode_end_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_aec_decode_init_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_aec_decode_aecwrap_14da976aa081fe6a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_aec_decode_end_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_aec_buffer_encode_aecwrap_14da976aa081fe6a(uintptr_t arg1);
extern swig_intgo _wrap_aec_buffer_decode_aecwrap_14da976aa081fe6a(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_aecwrap_14da976aa081fe6a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const LIBAEC_H int = 1

type SwigcptrAec_stream uintptr

func (p SwigcptrAec_stream) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAec_stream) SwigIsAec_stream() {
}

func (arg1 SwigcptrAec_stream) SetNext_in(arg2 *byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_next_in_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetNext_in() (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_aec_stream_next_in_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetAvail_in(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_avail_in_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetAvail_in() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_aec_stream_avail_in_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetTotal_in(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_total_in_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetTotal_in() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_aec_stream_total_in_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetNext_out(arg2 *byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_next_out_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetNext_out() (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_aec_stream_next_out_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetAvail_out(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_avail_out_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_type_5(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetAvail_out() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_aec_stream_avail_out_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetTotal_out(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_total_out_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetTotal_out() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_aec_stream_total_out_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetBits_per_sample(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_bits_per_sample_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetBits_per_sample() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_aec_stream_bits_per_sample_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetBlock_size(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_block_size_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetBlock_size() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_aec_stream_block_size_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetRsi(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_rsi_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetRsi() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_aec_stream_rsi_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetFlags(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_aec_stream_flags_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetFlags() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_aec_stream_flags_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAec_stream) SetState(arg2 Struct_SS_internal_state) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_aec_stream_state_set_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAec_stream) GetState() (_swig_ret Struct_SS_internal_state) {
	var swig_r Struct_SS_internal_state
	_swig_i_0 := arg1
	swig_r = (Struct_SS_internal_state)(SwigcptrStruct_SS_internal_state(C._wrap_aec_stream_state_get_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewAec_stream() (_swig_ret Aec_stream) {
	var swig_r Aec_stream
	swig_r = (Aec_stream)(SwigcptrAec_stream(C._wrap_new_aec_stream_aecwrap_14da976aa081fe6a()))
	return swig_r
}

func DeleteAec_stream(arg1 Aec_stream) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_aec_stream_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0))
}

type Aec_stream interface {
	Swigcptr() uintptr
	SwigIsAec_stream()
	SetNext_in(arg2 *byte)
	GetNext_in() (_swig_ret *byte)
	SetAvail_in(arg2 int64)
	GetAvail_in() (_swig_ret int64)
	SetTotal_in(arg2 int64)
	GetTotal_in() (_swig_ret int64)
	SetNext_out(arg2 *byte)
	GetNext_out() (_swig_ret *byte)
	SetAvail_out(arg2 int64)
	GetAvail_out() (_swig_ret int64)
	SetTotal_out(arg2 int64)
	GetTotal_out() (_swig_ret int64)
	SetBits_per_sample(arg2 uint)
	GetBits_per_sample() (_swig_ret uint)
	SetBlock_size(arg2 uint)
	GetBlock_size() (_swig_ret uint)
	SetRsi(arg2 uint)
	GetRsi() (_swig_ret uint)
	SetFlags(arg2 uint)
	GetFlags() (_swig_ret uint)
	SetState(arg2 Struct_SS_internal_state)
	GetState() (_swig_ret Struct_SS_internal_state)
}

const AEC_DATA_SIGNED int = 1
const AEC_DATA_3BYTE int = 2
const AEC_DATA_MSB int = 4
const AEC_DATA_PREPROCESS int = 8
const AEC_RESTRICTED int = 16
const AEC_PAD_RSI int = 32
const AEC_NOT_ENFORCE int = 64
const AEC_OK int = 0

func _swig_getAEC_CONF_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_AEC_CONF_ERROR_aecwrap_14da976aa081fe6a())
	return swig_r
}

var AEC_CONF_ERROR int = _swig_getAEC_CONF_ERROR()

func _swig_getAEC_STREAM_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_AEC_STREAM_ERROR_aecwrap_14da976aa081fe6a())
	return swig_r
}

var AEC_STREAM_ERROR int = _swig_getAEC_STREAM_ERROR()

func _swig_getAEC_DATA_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_AEC_DATA_ERROR_aecwrap_14da976aa081fe6a())
	return swig_r
}

var AEC_DATA_ERROR int = _swig_getAEC_DATA_ERROR()

func _swig_getAEC_MEM_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_AEC_MEM_ERROR_aecwrap_14da976aa081fe6a())
	return swig_r
}

var AEC_MEM_ERROR int = _swig_getAEC_MEM_ERROR()

const AEC_NO_FLUSH int = 0
const AEC_FLUSH int = 1

func Aec_encode_init(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_encode_init_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Aec_encode(arg1 Aec_stream, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_aec_encode_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Aec_encode_end(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_encode_end_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Aec_decode_init(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_decode_init_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Aec_decode(arg1 Aec_stream, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_aec_decode_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Aec_decode_end(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_decode_end_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Aec_buffer_encode(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_buffer_encode_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Aec_buffer_decode(arg1 Aec_stream) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_aec_buffer_decode_aecwrap_14da976aa081fe6a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type SwigcptrStruct_SS_internal_state uintptr
type Struct_SS_internal_state interface {
	Swigcptr() uintptr
}

func (p SwigcptrStruct_SS_internal_state) Swigcptr() uintptr {
	return uintptr(p)
}
